server:
  port: 8082
  servlet:
    session:
      timeout: 30000

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.demo.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug